name = "novdom_dev_tools"
version = "0.2.1"
target = "erlang"
gleam = ">= 1.1.0"

description = "Development Tooling and CLI for the novdom framework."
repository = { type = "github", user = "TobiasBinnewies", repo = "novdom_dev_tools" }
licences = ["MIT"]

internal_modules = ["lustre_dev_tools", "lustre_dev_tools/*"]

[dependencies]
argv = "~> 1.0"
filepath = "~> 1.0"
gleam_community_ansi = "~> 1.4"
gleam_erlang = "~> 0.25"
gleam_http = "~> 3.6"
gleam_json = "~> 1.0 or ~> 2.0"
gleam_otp = "~> 0.10"
gleam_package_interface = "~> 1.0"
gleam_stdlib = "~> 0.39 or ~> 1.0"
glint = ">=1.0.0 and < 2.0.0"
glisten = "~> 2.0"
mist = "~> 1.0"
simplifile = ">= 2.0.0 and < 3.0.0"
spinner = "~> 1.1"
tom = "~> 0.3"
wisp = "~> 0.14"
fs = "~> 8.6"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
term_size = ">= 1.0.1 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
